[boris]
  version = 1

[build.dist-validate]
  command = [["validate-respect"]]

[build.dist-core-7-10]
  command = [["master", "build", "dist-7-10", "-C", "tinfoil-core"]]

[build.dist-core-8-0]
  command = [["master", "build", "dist-8-0", "-C", "tinfoil-core"]]

[build.dist-core-cabal-test]
  command = [["master", "build", "dist-cabal-test", "-C", "tinfoil-core"]]

[build.branches-core-7-10]
  command = [["master", "build", "branches-7-10", "-C", "tinfoil-core"]]

[build.branches-core-8-0]
  command = [["master", "build", "branches-8-0", "-C", "tinfoil-core"]]

[build.branches-core-cabal-test]
  command = [["master", "build", "branches-cabal-test", "-C", "tinfoil-core"]]
