[boris]
  version = 1

[build.dist-validate]
  command = [["validate-respect"]]

[build.dist-7-10]

[build.dist-8-0]

[build.dist-cabal-test]

[build.branches-7-10]

[build.branches-8-0]

[build.branches-cabal-test]
